### ISSUE TITLE
Результат сохраняется в текущую папку

### ISSUE THREAD

**Issue by 1vanK** [MonkeyFirst/Urho3D-Blender-Animation-Markers#1]
Обычно текущая папка установлена в папку с блендером, поэтому если есть доступ, то результат сохраняется туда. Когда ты открываешь файл из папки, то текущая папка устанавливается туда. Нужно в функции open(action.name + ".xml", 'wt') указывать абсолютный путь. Правда непонятно, какой путь использовать, если файл еще не был сохранен. ПО идее лучше всего указывать путь вручную, как это сделано в экспортере Urho3D-blender. Кстати, а ты не планируешь добавить экспорт маркеров в официальный плагин?

**Comment by 1vanK** [comment]
Можно просто предупреждение выводить, если файл не был сохранен - типа сохраните файл перед экспортом маркеров

**Comment by 1vanK** [comment]
кажется можно вот это юзать https://www.blender.org/api/blender_python_api_2_63_release/bpy.types.BlendData.html#bpy.types.BlendData.filepath

**Comment by 1vanK** [comment]
вот этот код отлично работает

```
            if (isThisActionHasMarkers):
                # markers write
                if (bpy.data.filepath != ""):
                    file = open(os.path.dirname(bpy.data.filepath) + "/" + action.name + ".xml", 'wt')
                    file.write("<animation>\n")

                    for i, marker in enumerate(action.pose_markers):
                        if (self.normalizeMarkers == False):
                            print ("marker index: {0} frame: {1} name: {2}".format(i, marker.frame, marker.name))
                            file.write('    <trigger time="{0:.2f}" type="String" value="{1}" />\n'.format(marker.frame / fps, marker.name))
                        else:
                            print ("marker index: {0} normalizedtime: {1} name: {2}".format(i, marker.frame / lenAction, marker.name))
                            file.write('    <trigger normalizedtime="{0:.2f}" type="String" value="{1}" />\n'.format(marker.frame / lenAction, marker.name))


                    file.write("</animation>")                 
                    file.close()
                else:
                    self.report({'ERROR'}, "SAVE FILE PLS")
```

только проверку надо наверх вынести, то есть не для каждого экшена проверять, а в начале скрипта

**Comment by 1vanK** [comment]
А еще было бы здорово указать в описании плагина пункт меню, который нужно использовать для запуска скрипта, как это сделано во всех других плагинах

```
bl_info = {
    ...
    "location": "Object > Urho3D Markers Create",
    ...
```

**Comment by MonkeyFirst** [comment]
Мб ты PR cделаешь?) чтобы я смержил 

> Кстати, а ты не планируешь добавить экспорт маркеров в официальный плагин?

Там же есть какие-то маркеры, только для actions вроде бы нет. 
Да я и не знаю как из впаивать в офф плагин эти маркеры, мне проще моими сторонними мини плагинами наращивать новый функционал.

**Comment by 1vanK** [comment]
https://github.com/MonkeyFirst/Urho3D-Blender-Animation-Markers/pull/2
